name: restaurant_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"


dependencies:
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  path_provider: ^2.1.5
  bloc: ^8.1.3
  formz: ^0.7.0
  go_router: ^13.2.0
  gap: ^3.0.1
  json_annotation: ^4.8.1
  sqflite: ^2.4.1
  scrollable_list_tab_scroller: ^3.1.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  dart_style: ^2.3.6

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/